minecraft_container_name: minecraft-vanilla
minecraft_memory_gb: 12
minecraft_ops:
  - EqualMarcello
minecraft_difficulty: hard
minecraft_whitelist_enabled: true
minecraft_whitelist:
  - ItsBacara
  - Steve_Ohhhhh
  - heckinkiki
  - ShadOblivion
  - MastrIgnis9
  - MorganDoesStuff
  - EqualMarcello
  - theshortchris
  - Sir_Mannington
