servarr_openvpn_username: cedqMSR3Nu76FPDL79F9yomb
servarr_openvpn_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61656339623338646631343865323631303932373531393062356636626663333863303864666238
          3265636562393430386539336664366439653762353735640a663765663966393463616366343031
          38656665353238666630393362646663613530303139613039313636663763356236313837393637
          6230656230333732370a313761656666323636393932616634633764326239303864326130386134
          30396331646632336565666365323863636134323332656337326631353239353161

servarr_plex_url: https://plex.marcellodb.ca
servarr_plex_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61313236663039376137373666636661626430366539646362323632393732616466613337393631
          6631336530393538383334356431303135336634653565310a643935653338646161623164656666
          66633361643433303033393235313964626464376630396237653033353230653739333430396531
          3564396538643762320a336364373266333661306434356565626462353266313130363765323666
          62373837613638326261313533306636636664306166333433633130653934636566
servarr_plex_claim_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34636232323836353939633062396330376633633138613265643563316133646139613233653330
          6234363262373961356365363066363466323364636262320a303930646461656365306439306132
          61633764663165626636333261316137613662376562303431316132303265323862633666323637
          3332666166343038640a306439326531663630643132326333613637353638363233383037393930
          64666263386435313631656561623739646665346439333530383965646463346463

servarr_qbittorrent_url: https://qb.lab.marcellodb.ca
servarr_qbittorrent_username: marcello
servarr_qbittorrent_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65393231643730613061613961666166306133363665623964666566313532646339646364633733
          6463613035373037616163383732323030396661633936370a663030333962323666636566303130
          62663933626337393230316633663038633833373438363733306362303339643030373230353133
          3034383531666138330a643138333633333964343835666132643534656161303538326235393631
          6230

servarr_sonarr_url: https://sonarr.lab.marcellodb.ca
servarr_sonarr_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32363837383566626339623061323536396564343063346165626330633338336630373839636366
          6237306663376131363866306266313530633330656533630a356537376334383064396430353132
          62636536643439323133386133313134623834646130346639616264323631636333333330646464
          3939333235653164310a613233616631616435383637666336343166383064646662316434373064
          62326263616633376565306332643034656531336531313664643462333736383436393732323034
          3564646538363138306363353536336565393638626362656335

servarr_radarr_url: https://radarr.lab.marcellodb.ca
servarr_radarr_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64643036616466663039363133326530386532383838336234636233623564616161306137303532
          3831636566383662663339373634613930336166623765330a616331623865653739356139373864
          36353266626332343038376237623536633164613634336233386165626230323231626432373962
          6634343039646338610a393530356466386230313538636531346233626363333762383137316633
          35613135363031356137383339663032393030313464333064353135616339656138306461393833
          3133643330613766353266336666623535393237653662313063

servarr_prowlarr_url: https://prowlarr.lab.marcellodb.ca
servarr_prowlarr_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39393934363163383533306531643538616135633032663466613565303136616133393731353764
          6333666563306530326230623535356662613237363233640a383431636533663061383834613162
          35323538376365356161356330656438333436323731343039326661303236393839626561306561
          6231343337326235330a663763386362346330613062343237366434313334633431613565626366
          34393264376266383463303434623166393135316662363665663036366435346435396462373235
          6635663031333136623533323666323635373137633564653862

servarr_bazarr_url: https://bazarr.lab.marcellodb.ca
servarr_bazarr_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37376639373464346363343735636664373530316361663038313831383234366338353066303563
          3230343062373632616564633936386639633032646363620a313337333234386538313464626633
          61316534633564633765353161626138383931616661373039396539666138636631653834666663
          6666383161383563350a343339343165326638363863656335633435626639623933623039636130
          61663332313735303661323666633034613439363661333961626532653631396636653737316232
          6163383565306231323863393933646131333366343766336331

servarr_tv_volume:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.0.19.60,rw,nolock,hard,nointr
      device: ":/mnt/data01/media/tv"

servarr_downloads_volume:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.0.19.60,rw,nolock,hard,nointr
      device: ":/mnt/data01/media/downloads"
  
servarr_movies_volume:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=4,addr=10.0.19.60,rw,nolock,hard,nointr
      device: ":/mnt/data01/media/movies"
  
