docker_projects_directory: /opt/docker/
minecraft_container_name: minecraft
minecraft_container_version: latest
minecraft_memory_gb: 4
minecraft_port: 25565
minecraft_icon: ''
minecraft_ops: []
minecraft_whitelist_enabled: false
minecraft_whitelist: []
minecraft_difficulty: normal
minecraft_type: VANILLA
minecraft_cf_api_key: ''
minecraft_cf_modpack_url: ''
container_state: started
container_restart: false