ansible_become_pass: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34623730386361666234336539376166353132633465386536663736666430373336313865646261
          3031383337343737623737663236346437393162303433350a623037643864376632346630393363
          33626464326266366463646438386663653130303731346337373236663765636561313166623730
          3830356336376665360a336461316439306137393065623765666631373763363137316231353332
          3466
dns_servers:
  - 127.0.0.1
  - 8.8.8.8