npm_container_name: nginx_proxy_manager

minecraft_server_container_name: minecraft_server
minecraft_server_seed: -1541124385142397106
minecraft_server_container_uid: 9999
minecraft_server_container_gid: 9999
minecraft_server_memory_gb: 4
minecraft_server_icon_url: https://marcellod1.github.io/resources/img/server-icon.png
minecraft_server_ops:
  - EqualMarcello

portainer_container_name: portainer
portainer_admin_user: admin
portainer_admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31613631303331383735363830663432633238373162656266643161303163393163373135363132
          3066356136623766613136313964633962626665316532350a643862626332323130623834333662
          62613733313131393066343634653737313466626539343432306237623131663935663331626538
          3664363164376230660a323335323538353161343261333535306332663432326230326261376261
          31353336333935643335393134316434336637393337313163623438663436323635
portainer_endpoints:
  - name: docker02
    ip_address: 10.0.17.25